name: Track TryHackMe Labs

on:
  schedule:
    - cron: '0 0 * * *' # Runs automatically every day at midnight
  workflow_dispatch: # This specific line allows you to run it manually!

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python update_stats.py
      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@://github.com'
          git add README.md
          git commit -m "Update TryHackMe stats" || exit 0
          git push
